

services:
  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - "./frontend:/urs/share/nginx/html/frontend"
    restart: always
    depends_on:
      - backend